config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get "home/about" =>"homes#about", as: "about"
  patch 'books/:id' => 'books#update', as: 'update_book'
  patch 'users/:id' => 'users#update', as: 'update_user'
  resources :books
  resources :users

  resources :post_images do
    resource :favorite
    resources :post_comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name, length: { in: 2..20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
 before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    @user_path
  end


  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  # 投稿データの保存
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  #def destroy
    #Book.find(params[:id]).destroy
    #redirect_to book_path(params[:book_id])
  #end

  def edit
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      #@book = Book.find(params[:id])
      render :edit
    end
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    is_matching_login_user
    @user = User.find(params[:id])

  end



  def update
    #is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @user = current_user
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_sidebar.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <div>
    <%= image_tag user.get_profile_image(100,100) %>
  </div>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div>
    <%= link_to edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block' do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>

  <h2 class="mt-3">New book</h2>
    <%= form_with model: Book.new do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_field :body %>
      <h4><%= f.submit 'Create Book' %></h4>
    <% end %>
</div>

app/views/books/edit.html.erb
<p id="notice"></p>
  <div class="container px-5 px-sm-0">
      <div id="error_explanation">
        <% if @book.errors.any? %>
          <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h>
            <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
              <h4>Title</h4>
              <%= f.text_field :title %>
              <h4>Opinion</h4>
              <%= f.text_field :body %>
              <h4><%= f.submit 'Update Book' %></h4>
            <% end %>
            <%= link_to book_path(@book.id) do %>
              Show
            <% end %>
             |
            <%= link_to books_path do %>
              Back
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div id="error_explanation">
      <% if @book.errors.any? %>
        <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="row">
      <%= render 'sidebar', user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.file_field :title %>
  <h4>Opinion</h4>
  <%= f.text_field :opinion %>
  
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'sidebar', user: @book.user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@book.user) do %>
              <%= image_tag @book.user.get_profile_image(100,100) %>
            <% end %>

            <br>
            <%= link_to user_path(@book.user) do %>
              <%= @user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book.id) do %>
              <%= @book.title %>
            <% end %>
          </td>
          <td><%= @book.body %></td>
          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book),class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete , data: {confirm: '本当に消しますか？'}, class: "btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to
        <i class="fa-solid fa-book"></i>Bookers!
      </h1>
    </div>
  </div>

app/views/homes/top.html.erb
<p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1 class="px-3 mx-auto">Welcome to
          <i class="fa-solid fa-book"></i>Bookers!
        </h1>
        <p>
          In
          <i class="fa-solid fa-book"></i>
          <strong>Bookers</strong>
          ,
        </p>
        <p>
          you can share and exchange your opinions , inpressions , and emotions
        </p>
        <p>
          about various books!
        </p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <td>
              <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sing_in" %>
            </td>
          </div>
          <div class="row">
            <td>
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sing_up" %>
            </td>
        </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/ef8e0ab2ed.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class:"navbar-brand" do %>
            <span>Bookers</span>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user), class:"nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path, class:"nav-link text-light" do %>
                  <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path,class:"nav-link text-light" do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path, class:"nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class:"nav-link text-light" do %>
                  <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                  <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <p id="notice"><%= flash[:notice] %></p>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <div id="error_explanation">
        <% if @user.errors.any? %>
          <h2><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <h1>User info</h>
          <%= form_with model: @user, url: update_user_path(@user.id), method: :patch do |f| %>
            <h4>Name</h4>
            <%= f.text_field :name %>

            <h4>Introduction</h4>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>

            <h4>Introduction</h4>
            <%= f.text_field :introduction %>
            <h4><%= f.submit 'Update User' %></h4>
          <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div class= "container px-5 px-sm-0">
  <div class="row">

    <%= render 'books/sidebar', user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thred>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thred>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.get_profile_image(100,100) %>
            </td>
            <td><%= user.name %></td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'books/sidebar', user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>